server:
  port: 80
spring:
  application:
    name: microservicecloud-dept-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id:  microservicecloud-dept80 #自定义服务名称
    prefer-ip-address: true